/* AUTO-AB v8.84 — Carte grise dédiée sur la fiche véhicule */
(function () {
  'use strict';

  let currentCarteGrise = null;
  let originalCloseDocModal = null;
  let originalOpenAddDocumentModal = null;

  const normalize = value => String(value || '').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const docId = doc => doc?.id ?? doc?.idDocument ?? '';
  const docName = doc => doc?.nom || doc?.nomFichier || 'Carte grise';
  const docLink = doc => doc?.lienDrive || doc?.lien || doc?.url || '';
  const docCategory = doc => normalize(doc?.categorie || doc?.type || '');
  const docVehicle = doc => String(doc?.immatriculation || doc?.idVehicule || doc?.vehiculeId || doc?.VehiculeID || '').trim();
  function activeVehicle(){return String((typeof vehicleDetailImmat!=='undefined'&&vehicleDetailImmat)||(typeof selectedVehicule!=='undefined'&&selectedVehicule)||localStorage.getItem('activeVehicleAB')||'').trim();}
  function findCarteGrise(immat){const docs=Array.isArray(window.data?.documents)?window.data.documents:[];return docs.filter(doc=>docVehicle(doc)===immat&&(doc.statut||'Actif')!=='Archivé'&&docCategory(doc).includes('carte grise')).sort((a,b)=>String(b.dateUpload||b.date||'').localeCompare(String(a.dateUpload||a.date||'')))[0]||null;}
  function injectStyles(){if(document.getElementById('carteGriseStyles'))return;const style=document.createElement('style');style.id='carteGriseStyles';style.textContent='.vehicle-registration-row{display:flex;align-items:center;justify-content:space-between;gap:16px;min-height:64px;padding:11px 13px;margin-bottom:12px;border:1px solid #dfe6ef;border-radius:9px;background:#f8fafc}.vehicle-registration-info{min-width:0;display:flex;align-items:center;gap:12px}.vehicle-registration-icon{width:36px;height:36px;flex:0 0 36px;border:1px solid #c9d7e8;border-radius:8px;display:inline-flex;align-items:center;justify-content:center;background:#fff;color:#185fa5;font-size:16px}.vehicle-registration-text{min-width:0}.vehicle-registration-title{font-size:13px;font-weight:800;color:#102a43}.vehicle-registration-meta{margin-top:3px;font-size:11px;color:#667085}.vehicle-registration-actions{display:flex;gap:7px}.vehicle-registration-btn{min-height:32px;padding:0 10px;border:1px solid #9eb9da;border-radius:7px;background:#fff;color:#185fa5;font-size:11px;font-weight:700}.vehicle-registration-btn.primary{background:#185fa5;color:#fff;border-color:#185fa5}@media(max-width:620px){.vehicle-registration-row{align-items:flex-start;flex-direction:column}.vehicle-registration-actions{width:100%}.vehicle-registration-btn{flex:1}}';document.head.appendChild(style);}
  function genericDocumentsHtml(docs){if(!docs.length)return '';return '<div class="vehicle-other-documents-title">Autres documents</div>';}
  window.renderVehicleDetailDocuments=function(){const box=document.getElementById('vehicleDetailDocuments');if(!box)return;const immat=activeVehicle(),allDocs=(Array.isArray(window.data?.documents)?window.data.documents:[]).filter(doc=>docVehicle(doc)===immat&&(doc.statut||'Actif')!=='Archivé'),cg=findCarteGrise(immat),other=allDocs.filter(doc=>doc!==cg&&!docCategory(doc).includes('carte grise')&&!docCategory(doc).includes('entretien cout'));box.innerHTML=cg?`<div class="vehicle-registration-row"><div class="vehicle-registration-info"><span class="vehicle-registration-icon"><i class="bi bi-card-text"></i></span><div><div class="vehicle-registration-title">Carte grise</div><div class="vehicle-registration-meta">${safeText(docName(cg))}</div></div></div><div class="vehicle-registration-actions"><button class="vehicle-registration-btn" onclick="viewCarteGriseFromDetail()">Voir</button><button class="vehicle-registration-btn" onclick="openCarteGriseFromDetail()">Remplacer</button></div></div>`:`<div class="vehicle-registration-row"><div class="vehicle-registration-info"><span class="vehicle-registration-icon"><i class="bi bi-card-text"></i></span><div><div class="vehicle-registration-title">Carte grise</div><div class="vehicle-registration-meta">Aucune carte grise enregistrée</div></div></div><div class="vehicle-registration-actions"><button class="vehicle-registration-btn primary" onclick="openCarteGriseFromDetail()">Ajouter</button></div></div>`;};
  function restoreDocumentModalButton(){const submit=document.querySelector('#docModal .form-actions .btn-success');if(submit){submit.onclick=window.submitDocument;submit.innerHTML='📤 Charger et enregistrer';}currentCarteGrise=null;}
  if(typeof window.closeDocModal==='function'){originalCloseDocModal=window.closeDocModal;window.closeDocModal=function(){const r=originalCloseDocModal.apply(this,arguments);restoreDocumentModalButton();return r;};}
  if(typeof window.openAddDocumentModal==='function'){originalOpenAddDocumentModal=window.openAddDocumentModal;window.openAddDocumentModal=function(){restoreDocumentModalButton();return originalOpenAddDocumentModal.apply(this,arguments);};}
  window.openCarteGriseFromDetail=function(){const immat=activeVehicle();if(!immat)return showMsg('Aucun véhicule sélectionné','err');selectedVehicule=immat;currentCarteGrise=findCarteGrise(immat);originalOpenAddDocumentModal?originalOpenAddDocumentModal():openAddDocumentModal();const submit=document.querySelector('#docModal .form-actions .btn-success');if(submit)submit.onclick=window.saveCarteGriseFromDetail;};
  window.viewCarteGriseFromDetail=function(){const doc=findCarteGrise(activeVehicle());if(!doc||!docLink(doc))return showMsg('Aucune carte grise disponible','err');viewDocument(docName(doc),docLink(doc),doc.type||doc.categorie||'Carte grise');};
  window.saveCarteGriseFromDetail=async function(){const im=activeVehicle(),file=typeof selectedFile!=='undefined'?selectedFile:null;if(!file)return showErrorInModal('docModal','Sélectionne la carte grise');try{const lienDrive=await uploadFileToGoogleDrive(file);const body={action:'createDocument',immatriculation:im,categorie:'Carte grise',nom:'Carte grise - '+im,date:'',description:'Carte grise du véhicule',lienDrive};await postAppsScriptJson(body);await loadData();closeDocModal();renderVehicleDetailDocuments();showMsg('Carte grise enregistrée ✅','ok');}catch(e){showMsg('Erreur carte grise : '+(e?.message||e),'err');}};
  function loadMaintenanceCostsModule(){const old=document.querySelector('script[data-autoab-maintenance-costs]');if(old)old.remove();const script=document.createElement('script');script.src='entretien-couts.js?v=884';script.async=false;script.dataset.autoabMaintenanceCosts='1';document.body.appendChild(script);}
  function forceDisplayedVersion(){const badge=document.getElementById('appVersionBadge');if(badge)badge.textContent='v8.84';document.documentElement.dataset.appVersion='8.84';}
  injectStyles();loadMaintenanceCostsModule();forceDisplayedVersion();document.addEventListener('DOMContentLoaded',forceDisplayedVersion);setTimeout(forceDisplayedVersion,0);setTimeout(forceDisplayedVersion,500);
})();