/* AUTO-AB v8.97 — Carte grise suppression modale */
(function () {
'use strict';
const previousOpenCarteGrise=window.openCarteGriseFromDetail;
const previousDelete=window.deleteCurrentDocumentFromModal;
function getCg(){try{return typeof findCarteGrise==='function'?findCarteGrise(activeVehicle()):null;}catch(_){const d=(typeof data!=='undefined'&&data&&Array.isArray(data.documents))?data.documents:[];const im=String((typeof vehicleDetailImmat!=='undefined'&&vehicleDetailImmat)||(typeof selectedVehicule!=='undefined'&&selectedVehicule)||'').trim();return d.filter(x=>String(x.immatriculation||x.idVehicule||'').trim()===im&&String(x.categorie||x.type||'').toLowerCase().includes('carte grise')).slice(-1)[0]||null;}}
function cgId(d){return d?.id??d?.idDocument??'';}
function ensureCgDelete(){const actions=document.querySelector('#docModal .form-actions');if(!actions)return;let b=document.getElementById('cgDeleteBtn');if(!b){b=document.createElement('button');b.type='button';b.id='cgDeleteBtn';b.className='btn';b.style.cssText='margin-right:auto;background:#fff;color:#c62828;border:1px solid #d86464;display:none';b.innerHTML='<i class="bi bi-trash"></i> Supprimer';actions.insertBefore(b,actions.firstChild);}b.onclick=async()=>{const cg=getCg(),id=cgId(cg);if(!id)return;const ok=typeof showConfirm==='function'?await showConfirm('Supprimer définitivement la carte grise ?', {title:'Supprimer la carte grise',confirmText:'Supprimer',danger:true}):confirm('Supprimer définitivement la carte grise ?');if(!ok)return;b.disabled=true;b.textContent='Suppression…';try{await postAppsScriptJson({action:'deleteDocument',id:String(id)});if(typeof data!=='undefined'&&data&&Array.isArray(data.documents))data.documents=data.documents.filter(x=>String(cgId(x))!==String(id));if(typeof writeDataCache==='function')writeDataCache(data);if(typeof closeDocModal==='function')closeDocModal();if(typeof renderVehicleDetailDocuments==='function')renderVehicleDetailDocuments();if(typeof renderDocuments==='function')renderDocuments();showMsg('Carte grise supprimée ✅','ok');}catch(e){showMsg('Erreur suppression : '+(e?.message||e),'err');}finally{b.disabled=false;b.innerHTML='<i class="bi bi-trash"></i> Supprimer';}};}
if(typeof previousOpenCarteGrise==='function')window.openCarteGriseFromDetail=function(){const r=previousOpenCarteGrise.apply(this,arguments);setTimeout(()=>{ensureCgDelete();const b=document.getElementById('cgDeleteBtn');if(b)b.style.display=getCg()?'inline-flex':'none';},0);return r;};
const oldClose=window.closeDocModal;if(typeof oldClose==='function')window.closeDocModal=function(){const r=oldClose.apply(this,arguments);const b=document.getElementById('cgDeleteBtn');if(b)b.style.display='none';return r;};
function version(){const b=document.getElementById('appVersionBadge');if(b)b.textContent='v8.97';document.documentElement.dataset.appVersion='8.97';}
ensureCgDelete();version();document.addEventListener('DOMContentLoaded',()=>{ensureCgDelete();version();});
})();