/* AUTO-AB v8.84 — Entretien HT en une seule modale, enregistrement robuste */
(function(){
'use strict';
const CATEGORY='Entretien coût', PREFIX='AUTOAB_COST_V1:';
let currentYearFilter=null;
const euro=v=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(v||0));
const round2=v=>Math.round((Number(v||0)+Number.EPSILON)*100)/100;
const norm=v=>String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const activeVehicle=()=>String((typeof vehicleDetailImmat!=='undefined'&&vehicleDetailImmat)||(typeof selectedVehicule!=='undefined'&&selectedVehicule)||localStorage.getItem('activeVehicleAB')||'').trim();
function parse(doc){if(!norm(doc?.categorie||doc?.type).includes('entretien cout'))return null;const raw=String(doc?.description||'');if(!raw.startsWith(PREFIX))return null;try{return {...JSON.parse(raw.slice(PREFIX.length)),id:doc.id??doc.idDocument??'',lienDrive:doc.lienDrive||doc.lien||'',nomDocument:doc.nom||doc.nomFichier||'',immatriculation:doc.immatriculation||doc.idVehicule||''};}catch(e){return null;}}
function records(){const im=activeVehicle();return (Array.isArray(window.data?.documents)?window.data.documents:[]).map(parse).filter(Boolean).filter(x=>String(x.immatriculation||im)===im).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));}
function years(rs){return [...new Set(rs.map(r=>String(r.date||'').slice(0,4)).filter(y=>/^\d{4}$/.test(y)))].sort((a,b)=>+b-+a);}
function totals(rs){return rs.reduce((a,r)=>(a.revision+=+r.revision||0,a.reparations+=+r.reparations||0,a.pneus+=+r.pneus||0,a.autres+=+r.autres||0,a.total+=+r.totalHT||0,a),{revision:0,reparations:0,pneus:0,autres:0,total:0});}
function styles(){if(document.getElementById('entretienCoutsStyles'))return;const s=document.createElement('style');s.id='entretienCoutsStyles';s.textContent=`.vehicle-cost-panel{background:#fff;border:1px solid #dfe6ef;border-radius:10px;margin:0 0 12px;overflow:hidden}.vehicle-cost-head{display:flex;align-items:center;justify-content:space-between;padding:10px 13px;border-bottom:1px solid #edf0f4}.vehicle-cost-title{font-size:14px;font-weight:800;color:#0d3a66}.vehicle-cost-add{height:32px;padding:0 11px;border:1px solid #185fa5;border-radius:7px;background:#185fa5;color:#fff;font-size:11px;font-weight:700}.vehicle-cost-years{display:flex;gap:6px;padding:9px 12px 0;overflow-x:auto}.vehicle-cost-year{border:1px solid #cfd8e5;background:#fff;border-radius:999px;padding:5px 10px;font-size:11px;font-weight:700;white-space:nowrap}.vehicle-cost-year.active{background:#eaf2ff;border-color:#185fa5;color:#185fa5}.vehicle-cost-metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;padding:10px 12px 12px}.vehicle-cost-metric{background:#f8fafc;border:1px solid #e5eaf0;border-radius:8px;padding:9px 10px}.vehicle-cost-label{display:block;font-size:9px;font-weight:800;text-transform:uppercase;color:#667085}.vehicle-cost-value{font-size:14px;font-weight:800}.vehicle-cost-history{padding:0 12px 12px}.vehicle-cost-table{width:100%;border-collapse:collapse;margin-top:8px}.vehicle-cost-table th,.vehicle-cost-table td{padding:7px 8px;border-bottom:1px solid #edf0f4;font-size:11px;text-align:left}.cost-modal-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.cost-modal-grid .full{grid-column:1/-1}.cost-summary-line{display:flex;justify-content:space-between;padding:10px 12px;border-radius:8px;margin-top:10px;font-size:12px;font-weight:700;background:#fff5f5;color:#b42318}.cost-summary-line.ok{background:#f1f8f3;color:#1f6b38}.cost-section{grid-column:1/-1;margin-top:3px;padding-top:10px;border-top:1px solid #e5e7eb;font-size:11px;font-weight:800;color:#0d3a66;text-transform:uppercase}.cost-file-state{font-size:11px;color:#667085;margin-top:5px}.cost-save-state{min-height:18px;margin-top:8px;font-size:11px;font-weight:700;color:#185fa5}
#vehicleDetailPage .vehicle-cost-add,#vehicleDetailPage .vehicle-registration-btn.primary,#vehicleDetailPage .vehicle-card-head .btn-success,#vehicleDetailPage .vehicle-docs-card .btn-success,#vehicleDetailPage button[onclick*="openAddDocumentModal"]{height:34px!important;min-height:34px!important;padding:0 12px!important;border-radius:7px!important;border:1px solid #155fa0!important;background:#155fa0!important;color:#fff!important;font-size:11px!important;font-weight:800!important;line-height:1!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:5px!important;box-shadow:none!important}#vehicleDetailPage .vehicle-cost-add:hover,#vehicleDetailPage .vehicle-registration-btn.primary:hover,#vehicleDetailPage .vehicle-card-head .btn-success:hover,#vehicleDetailPage .vehicle-docs-card .btn-success:hover,#vehicleDetailPage button[onclick*="openAddDocumentModal"]:hover{background:#104f86!important;border-color:#104f86!important}
@media(max-width:760px){.vehicle-cost-metrics{grid-template-columns:repeat(2,1fr)}.vehicle-cost-metric.total{grid-column:1/-1}.cost-modal-grid{grid-template-columns:1fr}.cost-modal-grid .full,.cost-section{grid-column:auto}.vehicle-cost-table{min-width:720px}.vehicle-cost-history{overflow-x:auto}}`;document.head.appendChild(s);}
function modal(){document.getElementById('maintenanceInvoiceModal')?.remove();document.getElementById('maintenanceVentilationModal')?.remove();const w=document.createElement('div');w.innerHTML=`<div class="modal" id="maintenanceInvoiceModal"><div class="modal-content" style="max-width:680px"><div class="modal-header">Ajouter une facture d’entretien</div><div class="cost-modal-grid"><div class="form-group"><label>Date *</label><input type="date" id="costDate"></div><div class="form-group"><label>Montant total HT *</label><input type="number" id="costTotalHT" min="0" step="0.01" oninput="updateMaintenanceVentilationTotal()"></div><div class="form-group"><label>Garage / fournisseur</label><input id="costSupplier"></div><div class="form-group"><label>Kilométrage</label><input type="number" id="costKm"></div><div class="form-group full"><label>Facture / justificatif</label><input type="file" id="costFile" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png"><div class="cost-file-state">PDF, JPG ou PNG — facultatif.</div></div><div class="cost-section">Ventilation HT</div><div class="form-group"><label>Révision / entretien courant</label><input type="number" id="costRevision" min="0" step="0.01" value="0" oninput="updateMaintenanceVentilationTotal()"></div><div class="form-group"><label>Réparations</label><input type="number" id="costRepairs" min="0" step="0.01" value="0" oninput="updateMaintenanceVentilationTotal()"></div><div class="form-group"><label>Pneus</label><input type="number" id="costTyres" min="0" step="0.01" value="0" oninput="updateMaintenanceVentilationTotal()"></div><div class="form-group"><label>Autres</label><input type="number" id="costOther" min="0" step="0.01" value="0" oninput="updateMaintenanceVentilationTotal()"></div><div class="form-group"><label>Pneus — train concerné</label><select id="costTyrePosition"><option value="">—</option><option>Avant</option><option>Arrière</option><option>4 pneus</option></select></div><div class="form-group"><label>Pneus — km au montage</label><input type="number" id="costTyreKm"></div></div><button type="button" class="btn" style="margin-top:8px" onclick="maintenanceAllRevision()">Tout en révision</button><div id="costVentilationSummary" class="cost-summary-line"><span>Ventilé : 0,00 € HT</span><span>Facture : 0,00 € HT</span></div><div id="costSaveState" class="cost-save-state"></div><div class="form-actions"><button class="btn btn-secondary" onclick="closeMaintenanceInvoiceModal()">Annuler</button><button id="costSaveBtn" class="btn btn-success" onclick="saveMaintenanceInvoice()" disabled>Enregistrer</button></div></div></div>`;document.body.append(...w.children);}
window.openMaintenanceInvoiceModal=function(){modal();const im=activeVehicle();if(!im)return showMsg('Aucun véhicule sélectionné','err');costDate.value=new Date().toISOString().slice(0,10);const v=(data?.vehicules||[]).find(x=>x.immatriculation===im);costKm.value=v?.kilometrage??v?.km??'';maintenanceInvoiceModal.classList.add('active');updateMaintenanceVentilationTotal();};
window.closeMaintenanceInvoiceModal=()=>document.getElementById('maintenanceInvoiceModal')?.classList.remove('active');
window.maintenanceAllRevision=function(){const total=round2(costTotalHT.value);costRevision.value=total?total.toFixed(2):'0';costRepairs.value=costTyres.value=costOther.value='0';updateMaintenanceVentilationTotal();};
window.updateMaintenanceVentilationTotal=function(){const total=round2(document.getElementById('costTotalHT')?.value),vent=round2(round2(document.getElementById('costRevision')?.value)+round2(document.getElementById('costRepairs')?.value)+round2(document.getElementById('costTyres')?.value)+round2(document.getElementById('costOther')?.value)),ok=total>0&&Math.abs(vent-total)<.01;const s=document.getElementById('costVentilationSummary');if(s){s.className='cost-summary-line'+(ok?' ok':'');s.innerHTML=`<span>Ventilé : ${euro(vent)} HT</span><span>Facture : ${euro(total)} HT</span>`;}const b=document.getElementById('costSaveBtn');if(b)b.disabled=!ok;};
function withTimeout(ms,label){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),ms);return {signal:controller.signal,done:()=>clearTimeout(timer),label};}
async function postJsonDirect(payload,label){const t=withTimeout(30000,label);try{const r=await fetch(APPS_SCRIPT_URL,{method:'POST',body:JSON.stringify(payload),signal:t.signal});const text=await r.text();let result={};try{result=text?JSON.parse(text):{};}catch(_){throw new Error(label+' : réponse serveur invalide');}if(!r.ok||result.ok===false||result.success===false||result.error)throw new Error(result.error||result.message||label+' impossible');return result;}catch(e){if(e?.name==='AbortError')throw new Error(label+' : délai dépassé (30 s)');throw e;}finally{t.done();}}
async function fileToBase64(file){if(!file)return '';if(file.size>10*1024*1024)throw new Error('La facture dépasse 10 Mo');return await new Promise((resolve,reject)=>{const reader=new FileReader();const timer=setTimeout(()=>reject(new Error('Lecture du fichier trop longue')),15000);reader.onload=()=>{clearTimeout(timer);const raw=String(reader.result||'');const p=raw.indexOf(',');const b64=p>=0?raw.slice(p+1):'';b64?resolve(b64):reject(new Error('Lecture du fichier impossible'));};reader.onerror=()=>{clearTimeout(timer);reject(new Error('Lecture du fichier impossible'));};reader.readAsDataURL(file);});}
window.saveMaintenanceInvoice=async function(){const im=activeVehicle(),date=costDate.value,totalHT=round2(costTotalHT.value),revision=round2(costRevision.value),reparations=round2(costRepairs.value),pneus=round2(costTyres.value),autres=round2(costOther.value),file=costFile.files?.[0]||null;if(!date)return showMsg('La date est obligatoire','err');if(!(totalHT>0))return showMsg('Le montant HT doit être supérieur à 0','err');if(Math.abs(round2(revision+reparations+pneus+autres)-totalHT)>=.01)return showMsg('La ventilation doit correspondre au total HT','err');const supplier=String(costSupplier.value||'').trim(),km=Number(costKm.value)||'',payload={date,totalHT,supplier,km,revision,reparations,pneus,autres,tyrePosition:pneus>0?costTyrePosition.value:'',tyreKm:pneus>0?(Number(costTyreKm.value)||''):''};const btn=costSaveBtn,state=document.getElementById('costSaveState');btn.disabled=true;btn.textContent='Enregistrement…';try{let link='';if(file){state.textContent='1/2 — Envoi du justificatif…';const base64=await fileToBase64(file);const up=await postJsonDirect({action:'uploadFile',fileName:file.name,vehicule:im,fileBase64:base64,fileType:file.type||'application/octet-stream'},'Envoi du justificatif');link=up.fileUrl||up.url||up.lienDrive||'';if(!link)throw new Error('Le justificatif a été envoyé mais aucun lien n’a été retourné');}state.textContent=file?'2/2 — Enregistrement de la dépense…':'Enregistrement de la dépense…';const title=`Entretien ${date}${supplier?' - '+supplier:''}`;const body={action:'createDocument',immatriculation:im,idVehicule:im,categorie:CATEGORY,nom:title,nomFichier:title,date,description:PREFIX+JSON.stringify(payload),lienDrive:link};const result=await postJsonDirect(body,'Enregistrement de la dépense');if(!Array.isArray(window.data.documents))window.data.documents=[];window.data.documents.push({...body,id:result.id||result.idDocument||('local-'+Date.now()),statut:'Actif'});if(typeof writeDataCache==='function')writeDataCache(window.data);state.textContent='Enregistré';closeMaintenanceInvoiceModal();renderMaintenanceCostPanel();if(typeof renderVehicleDetailDocuments==='function')renderVehicleDetailDocuments();showMsg('Facture d’entretien enregistrée ✅','ok');}catch(e){state.textContent='Échec : '+(e?.message||e);showMsg('Erreur entretien : '+(e?.message||e),'err');}finally{btn.disabled=false;btn.textContent='Enregistrer';}};
function history(rs){if(!rs.length)return '<div style="font-size:11px;color:#98a2b3;padding:8px 0">Aucune dépense sur cette période.</div>';return `<table class="vehicle-cost-table"><thead><tr><th>Date</th><th>Garage</th><th>Km</th><th>Révision</th><th>Réparations</th><th>Pneus</th><th>Autres</th><th>Total HT</th><th>Facture</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${formatFrDate(r.date)}</td><td>${safeText(r.supplier||'—')}</td><td>${r.km?Number(r.km).toLocaleString('fr-FR'):'—'}</td><td>${euro(r.revision)}</td><td>${euro(r.reparations)}</td><td>${euro(r.pneus)}${r.tyrePosition?'<br>'+safeText(r.tyrePosition):''}</td><td>${euro(r.autres)}</td><td><strong>${euro(r.totalHT)}</strong></td><td>${r.lienDrive?`<button class="ab-icon-btn view" onclick='viewDocument(${JSON.stringify(r.nomDocument||'Facture entretien')},${JSON.stringify(r.lienDrive)})'><i class="bi bi-eye"></i></button>`:'—'}</td></tr>`).join('')}</tbody></table>`;}
window.setMaintenanceCostPeriod=p=>{currentYearFilter=p==='cumul'?'cumul':String(p);renderMaintenanceCostPanel();};
window.renderMaintenanceCostPanel=function(){const page=document.getElementById('vehicleDetailPage'),hero=document.getElementById('vehicleDetailHero');if(!page||!hero||page.style.display==='none')return;let panel=document.getElementById('vehicleMaintenanceCostPanel');if(!panel){panel=document.createElement('div');panel.id='vehicleMaintenanceCostPanel';hero.insertAdjacentElement('afterend',panel);}const rs=records(),ys=years(rs);if(!currentYearFilter||(currentYearFilter!=='cumul'&&!ys.includes(currentYearFilter)))currentYearFilter=ys[0]||String(new Date().getFullYear());const selected=currentYearFilter==='cumul'?rs:rs.filter(r=>String(r.date).startsWith(currentYearFilter)),t=totals(selected);const buttons=[...ys.map(y=>`<button class="vehicle-cost-year ${currentYearFilter===y?'active':''}" onclick="setMaintenanceCostPeriod('${y}')">${y}</button>`),`<button class="vehicle-cost-year ${currentYearFilter==='cumul'?'active':''}" onclick="setMaintenanceCostPeriod('cumul')">Cumul</button>`].join('');panel.innerHTML=`<div class="vehicle-cost-panel"><div class="vehicle-cost-head"><div class="vehicle-cost-title"><i class="bi bi-cash-stack"></i> Coûts entretien HT</div><button class="vehicle-cost-add" onclick="openMaintenanceInvoiceModal()">+ Facture</button></div><div class="vehicle-cost-years">${buttons}</div><div class="vehicle-cost-metrics">${[['Révisions',t.revision],['Réparations',t.reparations],['Pneus',t.pneus],['Autres',t.autres],['Total HT',t.total]].map((x,i)=>`<div class="vehicle-cost-metric ${i===4?'total':''}"><span class="vehicle-cost-label">${x[0]}</span><span class="vehicle-cost-value">${euro(x[1])}</span></div>`).join('')}</div><div class="vehicle-cost-history"><details><summary>Historique ${currentYearFilter==='cumul'?'complet':currentYearFilter} — ${selected.length} facture${selected.length>1?'s':''}</summary>${history(selected)}</details></div></div>`;};
function patch(){if(typeof window.renderVehicleDetailPage!=='function'||window.renderVehicleDetailPage.__costPatched)return;const o=window.renderVehicleDetailPage;window.renderVehicleDetailPage=function(){const r=o.apply(this,arguments);renderMaintenanceCostPanel();return r;};window.renderVehicleDetailPage.__costPatched=true;}
function forceVersion(){const badge=document.getElementById('appVersionBadge');if(badge&&badge.textContent==='v8.84')badge.textContent='v8.98';document.documentElement.dataset.appVersion='8.98';}
styles();modal();patch();forceVersion();document.addEventListener('DOMContentLoaded',forceVersion);setTimeout(()=>{patch();renderMaintenanceCostPanel();forceVersion();},0);
})();

/* v8.100 — UX documents : modale compacte + description visible */
(function(){
'use strict';
function injectDocUxStyles(){
  let s=document.getElementById('docUxStylesV8100');
  if(!s){s=document.createElement('style');s.id='docUxStylesV8100';document.head.appendChild(s);}
  s.textContent=`
#docModal .modal-content{width:min(620px,94vw)!important;max-width:620px!important;max-height:92vh!important;overflow-y:auto!important;padding:0!important;border-radius:12px!important}
#docModal .modal-header{position:sticky!important;top:0!important;z-index:2!important;background:#fff!important;padding:16px 20px!important;margin:0!important;border-bottom:1px solid #e4e7ec!important;font-size:19px!important;font-weight:800!important;color:#0d3a66!important}
#docModal .modal-content>div:nth-child(2){padding:16px 20px 10px!important}
#docModal .form-group{margin-bottom:12px!important}
#docModal .form-group label{display:block!important;margin-bottom:5px!important;font-size:12px!important;font-weight:750!important;color:#344054!important}
#docModal #docNom,#docModal #docDate{height:40px!important;padding:8px 10px!important;border-radius:7px!important;font-size:13px!important}
#docModal #docDescription{min-height:72px!important;max-height:110px!important;padding:9px 10px!important;border-radius:7px!important;font-size:13px!important;line-height:1.35!important;resize:vertical!important}
#docModal .form-group+div[style*="dashed"]{padding:12px!important;margin:4px 0 8px!important;border:1.5px dashed #72a7d4!important;border-radius:9px!important;background:#f7fbff!important}
#docModal .form-group+div[style*="dashed"]>div:first-child{font-size:12px!important;margin-bottom:7px!important;color:#344054!important}
#docModal .form-group+div[style*="dashed"] .btn{height:38px!important;padding:0 12px!important;margin-bottom:5px!important;border-radius:7px!important;background:#155fa0!important;font-size:12px!important;font-weight:800!important}
#docModal #docFileName{font-size:10.5px!important;color:#667085!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
#docModal .form-actions{position:sticky!important;bottom:0!important;z-index:2!important;background:#fff!important;border-top:1px solid #e4e7ec!important;padding:11px 20px!important;margin:0!important;display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:8px!important;flex-wrap:nowrap!important}
#docModal .form-actions .btn{height:38px!important;min-height:38px!important;padding:0 14px!important;border-radius:7px!important;font-size:12px!important;font-weight:800!important;white-space:nowrap!important}
#docModal .form-actions .btn-success{background:#176b3a!important;border-color:#176b3a!important;color:#fff!important}
#docModal #docDeleteBtn{margin-right:auto!important;height:38px!important}
.vehicle-generic-doc-desc{margin-top:4px!important;font-size:11px!important;line-height:1.35!important;color:#344054!important;white-space:normal!important;overflow-wrap:anywhere!important}
@media(max-width:640px){#docModal .modal-content{width:96vw!important}.vehicle-generic-doc-desc{font-size:10.5px!important}}
`;
}
function appDocs(){try{return (typeof data!=='undefined'&&Array.isArray(data?.documents))?data.documents:(Array.isArray(window.data?.documents)?window.data.documents:[]);}catch(_){return Array.isArray(window.data?.documents)?window.data.documents:[];}}
function currentImmat(){return String((typeof vehicleDetailImmat!=='undefined'&&vehicleDetailImmat)||(typeof selectedVehicule!=='undefined'&&selectedVehicule)||localStorage.getItem('activeVehicleAB')||'').trim();}
function addDescriptions(){
  const im=currentImmat(); if(!im)return;
  const docs=appDocs().filter(d=>String(d.immatriculation||d.idVehicule||'').trim()===im);
  document.querySelectorAll('#vehicleDetailDocuments .vehicle-generic-doc-row').forEach(row=>{
    if(row.querySelector('.vehicle-generic-doc-desc'))return;
    const title=row.querySelector('.vehicle-generic-doc-title')?.textContent?.trim();
    if(!title)return;
    const doc=docs.find(d=>String(d.nom||d.nomFichier||'').trim()===title);
    const desc=String(doc?.description||'').trim();
    if(!desc||desc.startsWith('AUTOAB_COST_V1:'))return;
    const meta=row.querySelector('.vehicle-generic-doc-meta');
    if(!meta)return;
    const el=document.createElement('div');el.className='vehicle-generic-doc-desc';el.textContent=desc;meta.insertAdjacentElement('afterend',el);
  });
}
function patchRender(){
  const fn=window.renderVehicleDetailDocuments;
  if(typeof fn!=='function'||fn.__descPatched)return;
  window.renderVehicleDetailDocuments=function(){const r=fn.apply(this,arguments);setTimeout(addDescriptions,0);return r;};
  window.renderVehicleDetailDocuments.__descPatched=true;
}
function forceVersion(){const b=document.getElementById('appVersionBadge');if(b)b.textContent='v8.100';document.documentElement.dataset.appVersion='8.100';}
injectDocUxStyles();patchRender();forceVersion();document.addEventListener('DOMContentLoaded',()=>{injectDocUxStyles();patchRender();forceVersion();setTimeout(addDescriptions,0);});setTimeout(()=>{injectDocUxStyles();patchRender();forceVersion();addDescriptions();},600);setTimeout(addDescriptions,1400);
})();