const test=require('node:test'),assert=require('node:assert/strict'),P=require('../expenses-report');
const base=()=>({invoices:[],completion:{}});
const f={month:'2026-09',annual:false,category:'fuel'};
function valid(d,m){d.completion['intermarche|a|'+m]={supplier:'intermarche',account:'A',status:'Validé'};}
function bill(d,m,ht,plate='AA123AA'){d.invoices.push({id:m,supplier:'intermarche',account:'A',status:'active',lines:[{month:m,category:'fuel',plate,personId:'p',scope:plate?'assigned':'unassigned',amounts:{ht},litres:10}]});}
test('Missing import differs from validated zero, even for current month',()=>{const d=base();assert.equal(P.status(d,f,'2026-10-02').complete,false);valid(d,'2026-09');assert.equal(P.status(d,f,'2026-10-02').complete,true);assert.equal(P.status(d,f,'2026-09-30').complete,false);});
test('Comparison waits for both periods and all HT',()=>{const d=base();bill(d,'2026-08',10000);bill(d,'2026-09',5000);valid(d,'2026-09');assert.equal(P.compare(d,f,-1,'2026-10-02').delta,null);valid(d,'2026-08');assert.equal(P.compare(d,f,-1,'2026-10-02').percent,-50);d.invoices[0].lines[0].amounts.ht=null;assert.equal(P.compare(d,f,-1,'2026-10-02').eligible,false);});
test('Unknown assignments prevent misleading vehicle decrease',()=>{const d=base();bill(d,'2026-08',10000);bill(d,'2026-09',5000,'');valid(d,'2026-08');valid(d,'2026-09');assert.equal(P.compare(d,{...f,plate:'AA123AA'},-1,'2026-10-02').eligible,false);});
test('Annual cutoff and twelve-month transition retain negative amounts and archives',()=>{const d=base();bill(d,'2026-09',-150);bill(d,'2026-10',900);assert.equal(P.select(d,{...f,annual:true}).length,1);assert.equal(P.trend(d,f,'2026-10-02')[0].month,'2025-10');assert.equal(P.status(d,f,'2026-10-02').sum.total,-150);});
test('Zero or credit baseline never produces misleading percentage',()=>{const d=base();bill(d,'2026-09',100);valid(d,'2026-08');valid(d,'2026-09');const c=P.compare(d,f,-1,'2026-10-02');assert.equal(c.eligible,true);assert.equal(c.percent,null);assert.equal(c.delta,100);});
test('CSV escapes separators, newlines and spreadsheet formulas',()=>{const s=P.csv([['=HYPERLINK("bad")','a;b','line\nnext','-1,50']]);assert.ok(s.startsWith('\uFEFF'));assert.ok(s.includes("\"'=HYPERLINK"));assert.ok(s.includes('"a;b"'));assert.ok(s.includes('"line\nnext"'));});
test('PDF text escaped, paginated, byte offsets point to objects',()=>{const bytes=P.pdf(Array.from({length:90},(_,i)=>'Opération '+i+' (test) \\ HT - 12,50 €')),s=Buffer.from(bytes).toString('latin1');assert.match(s,/\/Count 3/);assert.ok(s.includes('\\(test\\)'));const offset=Number(s.match(/startxref\n(\d+)/)[1]);assert.equal(s.slice(offset,offset+4),'xref');});
